name: Build plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PLUGIN_UUID: dev.mantha.backgroundmusic-streamdeck
  PLUGIN_PATH: dev.mantha.backgroundmusic-streamdeck.sdPlugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run config
      - run: bun run build
      - run: bun run --bun validate ${{ env.PLUGIN_PATH }}
      - run: bun run --bun bundle ${{ env.PLUGIN_PATH }}
      - uses: actions/upload-artifact@v4
        with:
          name: backgroundmusic-streamdeck.streamDeckPlugin
          path: ${{ env.PLUGIN_UUID }}.streamDeckPlugin
      - run: zip -r ${{ env.PLUGIN_UUID }}.zip ${{ env.PLUGIN_PATH }}/
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLUGIN_PATH }}.zip
          path: ${{ env.PLUGIN_PATH }}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLUGIN_UUID }}.streamDeckPlugin
          path: ${{ env.PLUGIN_UUID }}.streamDeckPlugin
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.PLUGIN_PATH }}.zip
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.PLUGIN_UUID }}.streamDeckPlugin
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
      - name: Upload release artifacts
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ${{ env.PLUGIN_UUID }}.streamDeckPlugin ${{ env.PLUGIN_PATH }}.zip




