name: Build plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PLUGIN_PATH: dev.mantha.backgroundmusic-streamdeck.sdPlugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run config
      - run: bun run build
      - run: bun run --bun validate ${{ env.PLUGIN_PATH }}
      - run: bun run --bun bundle ${{ env.PLUGIN_PATH }}
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/head/main'

    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

