name: Build plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PLUGIN_PATH: dev.mantha.backgroundmusic-streamdeck.sdPlugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Task
        uses: arduino/setup-task@v2
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun run validate ${{ env.PLUGIN_PATH }}
      - run: bun run bundle ${{ env.PLUGIN_PATH }}

